server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  Host: postgres
  Port: 5432
  Username: doston
  Password: dostonlv
  DBName: task
  SSLMode: disable
  PgDriver: pgx